### ISSUE TITLE
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by nbansal90** [IceTTTb/NopeSAC#2]
Hey @cherubicXN ,

I was able to use the docker file for launching a container. I was also able to run the `inference`  code using a pretrained weight. But when I try to run the `evaluation` I fail with the following error:

`us000146@d833e98e7f7b:~/NopeSAC$ sh eval_scannet.sh
Traceback (most recent call last):
  File "eval.py", line 15, in <module>
    from detectron2.structures import BoxMode
  File "/home/us000146/anaconda3/lib/python3.8/site-packages/detectron2/structures/__init__.py", line 7, in <module>
    from .masks import BitMasks, PolygonMasks, polygons_to_bitmask
  File "/home/us000146/anaconda3/lib/python3.8/site-packages/detectron2/structures/masks.py", line 9, in <module>
    from detectron2.layers.roi_align import ROIAlign
  File "/home/us000146/anaconda3/lib/python3.8/site-packages/detectron2/layers/__init__.py", line 3, in <module>
    from .deform_conv import DeformConv, ModulatedDeformConv
  File "/home/us000146/anaconda3/lib/python3.8/site-packages/detectron2/layers/deform_conv.py", line 11, in <module>
    from detectron2 import _C
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory`

It seems like it has something to do with the cuda version. I see that base image we have used in the `DockerFile` is for 11.3 version. I have also collected current configuration from my end and they are:

- Python 3.8.5 (default, Sep  4 2020, 07:30:14)

- torch.__version__'2.0.0'

- (base) us000146@d833e98e7f7b:~$ nvcc --version

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2021 NVIDIA Corporation
Built on Mon_May__3_19:15:13_PDT_2021
Cuda compilation tools, release 11.3, V11.3.109
**Build cuda_11.3.r11.3/compiler.29920130_0**

Could you Please verify if you are able to get this working from your end with the Dockerfile which you have provided.

Regards,
Nitin Bansal

**Comment by nbansal90** [comment]
Looks like reinstalling detectron2 and pytorch3D, once the container is up, resolves the issue. Closing this for now.
